FROM node:11

WORKDIR /app

COPY ./services/users ./services/users

COPY ./services/common ./services/common

WORKDIR /app/services/common
RUN npm install

WORKDIR /app/services/users
RUN npm install

CMD npm run test
